Repository gigabit-clowns/xmipp4-core, pull requests merged in 2024-10, with the labels that each got.

#62 Reinstated pages
  .github/workflows/ghpages.yml
Labels: documentation

#63 Revert "Removed Doxyfile"
  doc/doxygen/CMakeLists.txt
  doc/doxygen/Doxyfile
Labels: documentation

#64 Try 2 for Doxygen
  .github/workflows/ghpages.yml
  doc/doxygen/Doxyfile
Labels: bug

#65 Added missing DSO export declarations
  include/xmipp4/core/compute/host_communicator.hpp
  include/xmipp4/core/compute/host_communicator_backend.hpp
  include/xmipp4/core/compute/host_communicator_manager.hpp
  include/xmipp4/core/interface_manager.hpp
  include/xmipp4/core/interface_registry.hpp
  include/xmipp4/core/plugin.hpp
  include/xmipp4/core/plugin_manager.hpp
Labels: bug

#66 Tests to fix doxygen
  doc/doxygen/CMakeLists.txt
  doc/doxygen/Doxyfile
Labels: bug

#68 Configure folders for SonarCloud
  .sonarcloud.properties
Labels: enhancement

#76 Move reduction operation to root
  include/xmipp4/core/communication/communicator.hpp
  include/xmipp4/core/reduction_operation.hpp
  include/xmipp4/core/reduction_operation.inl
Labels: enhancement
